# Generated by Django 3.2 on 2021-11-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
    ]
